--loop联系,不熟练就单曲循环
--分部门打印员工信息

--一.loop,使用记录类型
--1.loop...exit...
DECLARE
	TYPE VEMP IS RECORD(
		EMP_ID   EMPLOYEES.EMPLOYEE_ID%TYPE,
		EMP_NAME EMPLOYEES.LAST_NAME%TYPE,
		EMP_SAL  EMPLOYEES.SALARY%TYPE,
		EMP_DEP  EMPLOYEES.DEPARTMENT_ID%TYPE);
	IEMP VEMP;
	CURSOR EMPC IS
		SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
		  FROM EMPLOYEES
		 WHERE DEPARTMENT_ID = &IDEP;
BEGIN
	OPEN EMPC;
	LOOP
		EXIT WHEN EMPC%NOTFOUND;
		FETCH EMPC
			INTO IEMP;
		DBMS_OUTPUT.PUT_LINE(IEMP.EMP_ID || ' ' || IEMP.EMP_NAME || ' ' ||
							 IEMP.EMP_SAL || ' ' || IEMP.EMP_DEP);
	END LOOP;
	CLOSE EMPC;
END;
/
--双重退出条件
DECLARE
	INUM NUMBER := 1;
	JNUM NUMBER := 10;
BEGIN
	DBMS_OUTPUT.PUT_LINE('i...j');
	LOOP
		EXIT WHEN INUM > 10;
		EXIT WHEN JNUM = 5;
		INUM := INUM + 1;
		JNUM := JNUM - 1;
		DBMS_OUTPUT.PUT_LINE(INUM || '...' || JNUM);
	END LOOP;
END;
/

--2.while...loop...
DECLARE TYPE VEMP IS RECORD(EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE,
							EMP_NAME EMPLOYEES.LAST_NAME%TYPE,
							EMP_DEP EMPLOYEES.DEPARTMENT_ID%TYPE);
IEMP VEMP;
CURSOR EMPC IS
	SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE department_id=&idep;
BEGIN
	OPEN EMPC;
	FETCH EMPC
		INTO IEMP;
	WHILE EMPC%FOUND LOOP
		DBMS_OUTPUT.PUT_LINE(IEMP.EMP_ID || ' ' || IEMP.EMP_NAME || ' ' ||
							 IEMP.EMP_DEP);
		FETCH EMPC
			INTO IEMP;
	END LOOP;

	CLOSE EMPC;
END;
/

--3.for...loop...
DECLARE
	CURSOR empc IS SELECT * FROM employees WHERE department_id=&idep;
BEGIN
	FOR emp IN empc LOOP
    	dbms_output.put_line(emp.employee_id||' '||emp.last_name||' '||emp.salary||' '||emp.department_id||' '||emp.hire_date);
    END LOOP;
END;
/

