--带参数的游标
DECLARE
	MEMP EMPLOYEES%ROWTYPE;
	CURSOR EMPC(DEP_ID NUMBER, SAL NUMBER) IS
		SELECT *
		  FROM EMPLOYEES
		 WHERE DEPARTMENT_ID = DEP_ID
		   AND SALARY > SAL;
BEGIN
	OPEN EMPC(80, 7000);
	LOOP
		EXIT WHEN EMPC%NOTFOUND;
		FETCH EMPC
			INTO MEMP;
		DBMS_OUTPUT.PUT_LINE(MEMP.EMPLOYEE_ID || ' ' || MEMP.LAST_NAME || ' ' ||
							 MEMP.SALARY || ' ' || MEMP.DEPARTMENT_ID ||
							 '--->' || EMPC%ROWCOUNT);
	END LOOP;
	CLOSE EMPC;
END;
/

SELECT * FROM employees WHERE department_id=80 AND salary>7000;

--使用内存表



--自定义异常
DECLARE
	E_EMPS_REMAINING EXCEPTION;
	PRAGMA EXCEPTION_INIT(E_EMPS_REMAINING, -2292);
BEGIN
	DELETE FROM DEPARTMENTS WHERE DEPARTMENT_ID = &P_DEPTNO;
	COMMIT;
EXCEPTION
	WHEN E_EMPS_REMAINING THEN
		DBMS_OUTPUT.PUT_LINE('Cannot remove dept ' || TO_CHAR(&P_DEPTNO) ||
							 '. Employees exist. ');
        dbms_output.put_line(SQLCODE);
END;




