--子查询练习
--单行子查询，多行子查询
--1.谁的工资比abel的高
SELECT *
  FROM EMPLOYEES
 WHERE SALARY > (SELECT SALARY FROM EMPLOYEES WHERE LAST_NAME LIKE 'Abel');

--2.查询员工名为chen的manager的信息
SELECT *
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID =
       (SELECT MANAGER_ID FROM EMPLOYEES WHERE LAST_NAME LIKE 'Chen');

--3.查询job_id与141号员工相同，salary比143号员工多的员工姓名，job_id和salary
SELECT JOB_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 141;
SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 143;
SELECT FIRST_NAME || ' ' || LAST_NAME FULL_NAME, JOB_ID, SALARY
  FROM EMPLOYEES
 WHERE JOB_ID = (SELECT JOB_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 141)
   AND SALARY > (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 143);
--4.返回公司工资最小的员工的信息
SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

--5.查询最低工资大于50号部门最低工资的部门id和最低工资
SELECT DEPARTMENT_ID, MIN(SALARY)
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
HAVING MIN(SALARY) > (SELECT MIN(SALARY)
                        FROM EMPLOYEES
                       WHERE DEPARTMENT_ID = 50);

--5.5 显示工号最多的部门信息
SELECT *
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID =
       (SELECT DEPARTMENT_ID
          FROM EMPLOYEES
         GROUP BY DEPARTMENT_ID
        HAVING COUNT(EMPLOYEE_ID) = (SELECT MAX(COUNT(EMPLOYEE_ID))
                                      FROM EMPLOYEES
                                     GROUP BY DEPARTMENT_ID));
--多行子查询 ,内层返回多行记录
--6.查询其他部门中比job_id为'IT_PROG'部门任一工资低的员工的信息
--注意：比任一与任意大/小的区别
SELECT *
  FROM EMPLOYEES
 WHERE JOB_ID <> 'IT_PROG'
   AND SALARY < ANY
 (SELECT SALARY FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG');
 
 
 
 

