DECLARE
	E_EMPS_REMAINING EXCEPTION;
	PRAGMA EXCEPTION_INIT(E_EMPS_REMAINING, -2292);
BEGIN
	DELETE FROM DEPARTMENTS WHERE DEPARTMENT_ID = &P_DEPTNO;
	COMMIT;
EXCEPTION
	WHEN E_EMPS_REMAINING THEN
		DBMS_OUTPUT.PUT_LINE('Cannot remove dept ' || TO_CHAR(&P_DEPTNO) ||
							 '. Employees exist. ');
        dbms_output.put_line(SQLCODE);
END;
