--withµÄÊ¹ÓÃ
WITH DEPT_COSTS AS
 (SELECT DEP.DEPARTMENT_NAME, SUM(EMP.SALARY) AS DEPT_TOTAL
    FROM EMPLOYEES EMP, DEPARTMENTS DEP
   WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
   GROUP BY DEP.DEPARTMENT_NAME),
AVG_COST AS
 (SELECT SUM(DEPT_TOTAL) / COUNT(*) AS DEPT_AVG FROM DEPT_COSTS)
SELECT *
  FROM DEPT_COSTS
 WHERE DEPT_TOTAL > (SELECT DEPT_AVG FROM AVG_COST)
 ORDER BY DEPARTMENT_NAME;
