SELECT * FROM cux_order_headers_all;

SELECT * FROM CUX_ORDER_HEADERS_V;

HAND_PLSQL_AUTOCREATE;
CUX_ORDER_HEADERS_PKG;

CUX_ORDER_HEADERS_ALL;

cux_order_headers_pkg;
CUX_ORDER_HEADERS_ALL_PKG;

SELECT * FROM CUX_ORDER_HEADERS;


SELECT * FROM DBA_POLICIES T WHERE T.OBJECT_NAME LIKE 'CUX%';	
	
	BEGIN
		DBMS_RLS.DROP_POLICY(OBJECT_NAME  => 'CUX_ORDER_HEADERS'  ,
							 POLICY_NAME  =>   'ORG_SEC');
		     DBMS_RLS.DROP_POLICY(OBJECT_NAME  => 'CUX_ORDER_HEADERS_ALL'  ,
								  POLICY_NAME  =>   'ORG_SEC');
		        END;
        
        
SELECT CUST.CUSTOMER_ID,
	   CUST.CUSTOMER_NAME,
	   CUST.CUSTOMER_NUMBER,
	   CUST.CUSTOMER_TYPE
  FROM AR_CUSTOMERS CUST;
  
  
  SELECT * FROM cux_order_lines_all;
  SELECT * FROM cux.cux_order_lines_all;
  SELECT * FROM CUX_ORDER_LINES_V;
  CUX_ORDER_LINES_V;

SELECT * FROM cux_order_headers_all;

hand_plsql_autocreate;

cux_order_headers_pkg;

CUX_ORDER_HEADERS_V;

SELECT * FROM CUX_ORDER_LINES_ALL;
SELECT * FROM CUX_ORDER_LINES_V;

cux_order_lines_all_pkg;



SELECT header_id, order_number, description FROM
cux_order_headers_all;



SELECT * FROM CUX.CUX_FLODER_DEMO;

SQL="SELECT ORGANIZATION_ID, NAME
INTO :PROFILE_OPTION_VALUE, :VISIBLE_OPTION_VALUE
FROM HR_OPERATING_UNITS"
COLUMN="NAME(*)";


SELECT ORGANIZATION_ID, NAME
  INTO :PROFILE_OPTION_VALUE, :VISIBLE_OPTION_VALUE
  FROM HR_OPERATING_UNITS;
  
  
SELECT * FROM HR_OPERATING_UNITS;

