--高级1:高级子查询
--知识点1.多列子查询表达式
--例1.查询与141和174号员工的manager_id和department_id
--相同的其他员工的employee_id,manager_id,department_id
--a.传统方法
SELECT EMPLOYEE_ID, MANAGER_ID, DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE MANAGER_ID IN
	   (SELECT MANAGER_ID FROM EMPLOYEES WHERE EMPLOYEE_ID IN (141, 174))
   AND DEPARTMENT_ID IN
	   (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID IN (141, 174))
   AND EMPLOYEE_ID NOT IN (141, 174);
--b.高级,成对的查询,也可以是3个,重点
SELECT EMPLOYEE_ID, MANAGER_ID, DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE (MANAGER_ID, DEPARTMENT_ID) IN
	   (SELECT MANAGER_ID, DEPARTMENT_ID
		  FROM EMPLOYEES
		 WHERE EMPLOYEE_ID IN (141, 174))
   AND EMPLOYEE_ID NOT IN (141, 174);
--c.在from子句中使用子查询
--例2.返回比本部门平均工资高的员工的last_name,department_id,salary以及平均工资
--a.传统方法
SELECT LAST_NAME,
	   DEPARTMENT_ID,
	   SALARY,
	   ROUND((SELECT AVG(SALARY)
			   FROM EMPLOYEES EMP3
			  WHERE EMP3.DEPARTMENT_ID = EMP1.DEPARTMENT_ID
			  GROUP BY DEPARTMENT_ID),
			 2) AVG_SAL
  FROM EMPLOYEES EMP1
 WHERE SALARY > (SELECT AVG(SALARY)
				   FROM EMPLOYEES EMP2
				  WHERE EMP2.DEPARTMENT_ID = EMP1.DEPARTMENT_ID
				  GROUP BY DEPARTMENT_ID);

--b.form子句中使用子查询,重点
SELECT EMP1.LAST_NAME, EMP1.DEPARTMENT_ID, EMP1.SALARY, EMP2.AVG_SAL
  FROM EMPLOYEES EMP1,
	   (SELECT DEPARTMENT_ID, AVG(SALARY) AS AVG_SAL
		  FROM EMPLOYEES
		 GROUP BY DEPARTMENT_ID) EMP2
 WHERE EMP1.DEPARTMENT_ID = EMP2.DEPARTMENT_ID
   AND EMP1.SALARY > EMP2.AVG_SAL;        
   
--知识点2 单列子查询表达式 一行中只返回一列数据
--例1.显示员工的employee_id,last_name和loaction
--	  其中,若员工department_id与location_id为1800的department_id相同,
--	  则location为'Canada',其余则为则为'USA'
--a.失败的传统例子
SELECT EMP.EMPLOYEE_ID, EMP.LAST_NAME, LOC.LOCATION_ID
  FROM EMPLOYEES EMP, DEPARTMENTS DEP, LOCATIONS LOC
 WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
   AND DEP.LOCATION_ID = LOC.LOCATION_ID
   AND EMP.DEPARTMENT_ID =
	   (SELECT DEP1.DEPARTMENT_ID
		  FROM DEPARTMENTS DEP1
		 WHERE DEP1.LOCATION_ID = 1800);
--b.正解
SELECT EMPLOYEE_ID,
	   LAST_NAME,
	   (CASE DEPARTMENT_ID
		   WHEN
			(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE LOCATION_ID = 1800) THEN
			'Canada'
		   ELSE
			'USA'
	   END) LOACTIONS
  FROM EMPLOYEES;


--例2.查询员工的employee_id,last_name,要求按照员工的department_name 排序
--a.传统
SELECT EMP.EMPLOYEE_ID, EMP.LAST_NAME, DEP.DEPARTMENT_NAME
  FROM EMPLOYEES EMP, DEPARTMENTS DEP
 WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 ORDER BY DEP.DEPARTMENT_NAME;
--b.高级
SELECT EMPLOYEE_ID, LAST_NAME
  FROM EMPLOYEES EMP
 ORDER BY (SELECT DEPARTMENT_NAME
			 FROM DEPARTMENTS DEP
			WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID) ASC;



SELECT * FROM departments;
SELECT * FROM locations;


--高级2:相关子查询






