--1.分组练习
SELECT * FROM DEPARTMENTS;

SELECT MAX(SALARY) FROM EMPLOYEES;

SELECT MAX(FIRST_NAME) FROM EMPLOYEES;

SELECT COUNT(2) FROM EMPLOYEES;

--算奖金律的问题 , sum和count只计算非null
SELECT COMMISSION_PCT FROM EMPLOYEES;
SELECT AVG(COMMISSION_PCT),
       SUM(COMMISSION_PCT) / COUNT(COMMISSION_PCT),
       SUM(COMMISSION_PCT) / 107,
       SUM(COMMISSION_PCT) / COUNT(NVL(COMMISSION_PCT, 1))
  FROM EMPLOYEES;

SELECT COUNT(COMMISSION_PCT) FROM EMPLOYEES;

--部门平均工资高于5000的部门id及其平均工资
SELECT EMP.DEPARTMENT_ID, AVG(EMP.SALARY)
  FROM EMPLOYEES EMP
 GROUP BY EMP.DEPARTMENT_ID
HAVING AVG(EMP.SALARY) > 5000;

--查询各个管理者手下员工的最低工资，其中最低工资不能低于6000，没有管理者的员工不计算在内
SELECT MANAGER_ID, MIN(SALARY)
  FROM EMPLOYEES
 WHERE MANAGER_ID IS NOT NULL
 GROUP BY MANAGER_ID
HAVING MIN(SALARY) > 6000;

--查询所有部门的名字，location_id,员工数量和工资平均值
SELECT DEP.DEPARTMENT_NAME,
       DEP.LOCATION_ID,
       COUNT(EMP.EMPLOYEE_ID),
       AVG(EMP.SALARY)
  FROM EMPLOYEES EMP, DEPARTMENTS DEP
 WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID(+)
 GROUP BY DEP.DEPARTMENT_NAME, DEP.LOCATION_ID;

SELECT DEP.DEPARTMENT_NAME,
       DEP.LOCATION_ID,
       COUNT(EMP.EMPLOYEE_ID),
       AVG(EMP.SALARY)
  FROM EMPLOYEES EMP
 RIGHT JOIN DEPARTMENTS DEP
    ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
 GROUP BY DEP.DEPARTMENT_NAME, DEP.LOCATION_ID;

--查询公司在2001-2005年之间，每年雇佣的人数
SELECT * FROM EMPLOYEES;
SELECT HIRE_DATE, COUNT(HIRE_DATE)
  FROM EMPLOYEES
 WHERE TO_CHAR(HIRE_DATE, 'yyyy') IN
       ('2001', '2002', '2003', '2004', '2005')
 GROUP BY HIRE_DATE;

SELECT COUNT(*) "total",
       COUNT(DECODE(TO_CHAR(HIRE_DATE, 'yyyy'), '2001', 1, NULL)) "2001",
       COUNT(DECODE(TO_CHAR(HIRE_DATE, 'yyyy'), '2002', 1, NULL)) "2002",
       COUNT(DECODE(TO_CHAR(HIRE_DATE, 'yyyy'), '2003', 1, NULL)) "2003",
       COUNT(DECODE(TO_CHAR(HIRE_DATE, 'yyyy'), '2004', 1, NULL)) "2004",
       COUNT(DECODE(TO_CHAR(HIRE_DATE, 'yyyy'), '2005', 1, NULL)) "2005"
  FROM EMPLOYEES
 WHERE TO_CHAR(HIRE_DATE, 'yyyy') IN
       ('2001', '2002', '2003', '2004', '2005');
